### PR TITLE
Add L2TPv3 tunnel/session support to iproute2 module

### PR DESCRIPTION
**Pull request by emericv**
Add L2TPv3 tunnel/session support to iproute2 module:

Example of config to add two L2TPv3 session/two interfaces with a shared tunnel:

l2tptunnel_net1="remote 1.2.3.4 local 1.2.3.5tunnel_id 3 peer_tunnel_id 3 encap ip"
l2tpsession_net1="tunnel_id 3 session_id 3 peer_session_id 3"
config_net1="null"

l2tptunnel_net2="remote 1.2.3.4 local 1.2.3.5 tunnel_id 3 peer_tunnel_id 3 encap ip"
l2tpsession_net2="tunnel_id 3 session_id 4 peer_session_id 4"
config_net2="null"

### CODE REVIEW

**Comment by robbat2** [comment]
Please add this new functionality as a separate file (see macvlan.sh as an example), and include a block for net.example
Otherwise looks good.

**Comment by emericv** [comment]
Ok

**Comment by emericv** [comment]
done :)

**Comment by robbat2** [comment]
Passes a quick eyeball test; give me a bit to test it and review because it's one of the most complete submissions I've gotten in a while :-)

**Pull request merged**
