### PR TITLE
net/wpa_supplicant: change how we match wired connections

### PR DESCRIPTION
**Pull request by henning-schild**
Please let me know in case i have to create a Bug or something.

### CODE REVIEW

**Comment by robbat2** [comment]
A bug preferred, but also, let's not parse it with grep when we could do it in pure shell.
If we loop over it with the case statement, and use wireless as the fallback, probably quicker than the exec of grep.

Also wondering, what if multiple -D options are passed by the user, esp when multiple interfaces are used.

**Comment by henning-schild** [comment]
preferred!=required i will stick to github-only in that case

Ok, i thought about keeping the case but the regexp would not work there. Let me see how to do that in pure shell. Which shells need to work? I am guessing in my case (Linux amd64) it is using bash.

As far as i can tell the current implementation can not handle multiple -Ds. If -Dwired is found wireless=false gets set. And _is_wireless() gets one IFACE so there are no multiple interfaces. But i might be reading that wrong.

**Comment by robbat2** [comment]
Something like this (written quickly in the comment box, apologies for errors):
```
last_D=n seen_D=n
for i in ${opts} ; do
  if [ "$last_D" == "y" ]; then
    case $i in
      wired|roboswitch) wireless=false ;;
    esac
    last_D=n
 else
  case $i in
   -Dwired) wireless=false seen_D=y ;;
   -Droboswitch) wireless=false seen_D=y ;;
   -D) last_D=y seen_D=y ;;
   -N) ;; # TODO starts new interface
  esac
done
if [ "$seen_D" != "y" ]; then
  _is_wireless || return 0
fi 
```

Could also be done with `set -- ${opts}` and consuming via positional args

**Comment by henning-schild** [comment]
Thank your for proposing an implementation. But i am getting confused where the multiple interfaces should be coming from or how to test that. I would rather fix that one problem in one commit, where others could add the additional features ie "roboswitch", and multi-interface support.
Can i leave it up to you, maybe creating a bug for the "-Dwired" vs. "-D wired" after all?

**Comment by robbat2** [comment]
Yes, drop it to a bug in that case, and reference this PR

**Comment by henning-schild** [comment]
https://bugs.gentoo.org/638836

**Pull request closed without merging**
